### ISSUE TITLE
IPV6 Addresses

### ISSUE THREAD

**Issue by jamielsharief** [nuber-io/nuber#1]
Display the IPV6 addresses if enabled, in the user guide during setup maybe mention this if, if user wants to have enabled rather that saying accept defaults.

**Comment by amarc** [comment]
Just to signup myself on this one as I am one asked for this on LXD forums.

A.

**Comment by jamielsharief** [comment]
Progress

![image](https://user-images.githubusercontent.com/20553479/119139838-c2e08000-ba43-11eb-9398-59cf406c70f2.png)

![image](https://user-images.githubusercontent.com/20553479/119139898-d4c22300-ba43-11eb-9bb0-662005e38cb0.png)

**Comment by jamielsharief** [comment]
![image](https://user-images.githubusercontent.com/20553479/119141330-69795080-ba45-11eb-90bf-5418b5969011.png)

**Comment by amarc** [comment]
@jamielsharief this looks great,thanks. Maybe some "copy to clipboard" function on mouseover on IP(s).. Would be useful.

**Comment by jamielsharief** [comment]
Can you create a feature request (issue) for this, as this is interesting, and I would like to look at a few months down the line.
