### ISSUE TITLE
ipv6 addresses incorrectly stripped

### ISSUE THREAD

**Issue by vosdev** [nuber-io/nuber#25]
![image](https://user-images.githubusercontent.com/45820840/167172904-9fbaae38-d57d-490f-b0f0-4f3492f9a972.png)

ip addresses are split on :

Should be a reverse split on : so it's done on the last occurrence and not the first to support IPv6

in python this is .rsplit(':') instead of .split(':')

**Comment by jamielsharief** [comment]
I don't recall any splitting, i am guessing its some security thing or its the minify middleware, which you can try removing, but it should not be a problem.

https://github.com/nuber-io/nuber/blob/master/app/Http/Application.php#L38

**Comment by jamielsharief** [comment]
Can you give me a slightly modified version of the IP address that you are using, so i can test. I cant replicate the problem. I am testing with chrome, the only other thing i can think of is an extension that you are using which is intercepting the post data.

![image](https://user-images.githubusercontent.com/20553479/167252233-95898849-f427-45c9-b8c1-7b2a78340155.png)

**Comment by vosdev** [comment]
Well when you visit a new installation the pre-filled address is the URL you are visiting and I did not set a DNS record yet for my container so I visited the Nuber application via direct ipv6 address like https://[2001:db8::abc]

That address `[2001:db8::abc]` gets prefilled in the Address field but it was split on the first `:` leaving me only with `[2001`

I reset my nuber application like you suggested in the other issue but this time I already had set a DNS record so now the pre-filled address was set to `nuber.example.com` like my domainname for my nuber container


Not a big issue of course, just something I run into a lot because I do everything via IPv6 and most people do not so small bugs like these in software are often overlooked.
