### ISSUE TITLE
LXD Projects and Nuber

### ISSUE THREAD

**Issue by vosdev** [nuber-io/nuber#28]
Hey hello,

I utilize LXD projects to separate my instances into 5 different groups, for example:

```
~
root @ epyc # lxc project ls
+------------------+--------+----------+-----------------+----------+---------------------+---------+
|       NAME       | IMAGES | PROFILES | STORAGE VOLUMES | NETWORKS |     DESCRIPTION     | USED BY |
+------------------+--------+----------+-----------------+----------+---------------------+---------+
| cloudnative      | YES    | YES      | YES             | NO       |                     | 18      |
+------------------+--------+----------+-----------------+----------+---------------------+---------+
| default          | YES    | YES      | YES             | YES      | Default LXD project | 6       |
+------------------+--------+----------+-----------------+----------+---------------------+---------+
| legacy (current) | NO     | NO       | NO              | NO       |                     | 11      |
+------------------+--------+----------+-----------------+----------+---------------------+---------+
```

How can I switch between projects in the nuber web interface? I do not use the default profile except for my profiles so without the ability to switch projects..

**Comment by vosdev** [comment]
Thinking in solutions instead of problems I wanted to try and add a new host through a generated token restricted to a single project:
```
lxc config trust add --name nuber/legacy --projects legacy
```

But nuber only supports authentication through the core trust password?

**Comment by jamielsharief** [comment]
The project feature is not or planned to be added in Nuber. I had wanted to implement a tag based solution, which would be similar.

**Comment by jamielsharief** [comment]
When you add a host there is option at the bottom for the certificate. Either way, the instructions also says after you add the host to remove the password, its only needed once to process the certificate.

**Comment by jamielsharief** [comment]
The host password is only required for the initial adding the host, after that , it is not used. You can remove once you have connected to the server.

**Comment by vosdev** [comment]
If you add support for adding a host through a token you do not have to build this complex feature but rather have the users "switch host" and authenticate to the LXD API using the certificate that is restricted to project XYZ

```
root @ epyc # lxc config trust add --projects legacy
Please provide client name: nuber/legacy
Client nuber/legacy certificate add token:
eyJjbGllbnRfbmFtZSI6Im51YmVyL2xlZ2FjeSIsImZpbmdlcnByaW50IjoiOGNjZTAwNjIxZDFjZmQxNGNjZmFkNjcyNjE4MzQzOWM2YzdhYjEzMTVm.NkOSIsImFkZHJlc3NlcyI6WyIxOTIuMTY4LjE3OC41Ojg0NDMiLCIxOTIuMTY4LjE3OC43...
```



> When you add a host there is option at the bottom for the certificate. Either way, the instructions also says after you add the host to remove the password, its only needed once to process the certificate.

I do not have that option. I put the certificate token into the password field but I run into the error that the IP address is already added.

![image](https://user-images.githubusercontent.com/45820840/168124009-e48459f7-aed5-4247-a962-5323c47f78fc.png)

**Comment by jamielsharief** [comment]
Nuber was never created to offer a web UI to the whole lxd API. It was created as an easy to use virtualization platform which uses lxd (some of features) under the hood.

**Comment by jamielsharief** [comment]
On the add host screen above there is a link at the bottom which says host configuration options , if you click that you can download the certificate, and then add that manually to your server. The password is just used to intially transfer that over. The only way I can I see you using multiple hosts with same ipadress is adding entry to the hosts file,so each host has a different address.
